### PR TITLE
foreigns

### LINKED ISSUE #4: fully port platform api
And make nullable values `Maybe` 
Also add some tests

### PR DESCRIPTION
**Pull request by cryogenian**
fixes #4 
@jonsterling @beckyconning what do you think? Isn't it too verbose?

### CODE REVIEW

**Comment by jonsterling** [comment]
I think it is fine; my only question, though, is why this is in `Aff`.

**Comment by cryogenian** [comment]
- `Eff` handles failure by wrapping `Platform` to `Maybe`, `Aff` throws exception.  
- I like `Aff` :smile: 

I can rename `getPlatform` to `getPlatformAff` if you like

**Comment by jonsterling** [comment]
@cryogenian We can also throw an exception in the `Eff` version, though, right? I guess I'm having trouble seeing why we would want to require `Aff` (thus making it harder for a user to run this code from an `Eff` program, in addition to introducing a spurious dependency), when it does not seem to gain us anything substantive; `Aff` can of course be used to model synchronous computations, but I do not know if that is sufficient justification to introduce it.

I like `Aff` too :smile:, but it feels like we should only introduce it where it simplifies an API (and its consumption), or somehow improves correctness or reliability; is there a sense in which `Aff` is simplifying the API here that adding `EXCEPTION` to the `Eff` row would not suffice to do?

**Comment by cryogenian** [comment]
@jonsterling I removed `Aff`. Now `getPlatform` has `MonadEff` constraint and returns `Maybe Platform`. I think anyone can easily add combinator `throwIfNothing:: forall m e. (MonadError e m) => m (Maybe a) -> m a`, there is no any purpose to add it in this lib.
Thank you very much for review!

**Comment by jonsterling** [comment]
@cryogenian thank you!

:+1: I'm happy with this PR; @beckyconning any other comments?

**Comment by beckyconning** [comment]
Looks good. Yeah it is quite long but I think it needs to be right now.

**Comment by cryogenian** [comment]
Thanks! I think that we can remove lot of boilerplate after 0.7.4 update by adding `Generic` instances

**Pull request merged**
