### PR TITLE
Add travis integration, fix build

### LINKED ISSUE #3: add .travis.yml

### PR DESCRIPTION
**Pull request by jonsterling**
This resolves #3 by adding a Travis configuration. Additionally, I realized that the build doesn't work fresh, so I added some resolutions to the bower file (does anybody know of a better thing to do? I always feel dirty doing that).

Additionally, I corrected added a license field to `package.json` and corrected the format of the one in `bower.json`.

@cryogenian or @beckyconning Would one of you review this please? thanks!

### CODE REVIEW

**Comment by cryogenian** [comment]
`purescript-base` has not been updated for 2 monthes. I think it causes bower conflicts. 
Anyway :+1:

**Comment by jonsterling** [comment]
Thanks for the info & review, @cryogenian! Is there any obstacle for us to fix `purescript-base`?

**Comment by jdegoes** [comment]
No, in fact, please do update base!

**Comment by jonsterling** [comment]
@jdegoes OK, sounds GREAT! Doing that will help resolve a number of frustrating issues across our packages I think :smile:

**Pull request merged**
