### PR TITLE
Added platform.js as a dependency

### PR DESCRIPTION
**Pull request by beckyconning**

### CODE REVIEW

**Comment by cryogenian** [comment]
Could you specify this package through npm and `require` it in purescript code? 
It would be much more convenient I think, because we can specify lib version in `package.json` and then it works. In case of `bower.json` we need to add additional step for concatenation of `platform.js` with our script.

**Comment by cryogenian** [comment]
Ah, I see it was already mentioned in `package.json` so we need not to mention it in `bower.json`

**Comment by beckyconning** [comment]
still need to mention it in bower.json for when installed through bower

**Comment by cryogenian** [comment]
I close this because we really need not this in `bower.json`

**Pull request closed without merging**
